# Generated by Django 3.1 on 2020-10-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='password',
            new_name='description',
        ),
        migrations.AddField(
            model_name='user_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='price',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
